project_name: f1viewer
builds:
  - 
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
archives:
  -
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
nfpms:
  -
    description: TUI client for F1TV
    license: GPL-3.0-only
    homepage: https://github.com/SoMuchForSubtlety/f1viewer/
    maintainer: SoMuchForSubtlety <s0muchfrsubtlety@gmail.com>
    replacements:
      darwin: macOS
    formats:
      - deb
      - rpm
    dependencies:
      - mpv
    recommends:
      - xclip
brews:
  -
    description: TUI client for F1TV
    homepage: https://github.com/SoMuchForSubtlety/f1viewer/
    folder: Formula
    github:
      owner: SoMuchForSubtlety
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    dependencies:
      - mpv
