project_name: f1viewer
builds:
  - id: windows
    goos:
      - windows
    goarch:
      - amd64
  - id: linux
    goos:
      - linux
    goarch:
      - amd64
  - id: mac
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      darwin: macOS
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
nfpms:
  - description: TUI client for F1TV
    license: GPL-3.0-only
    homepage: https://github.com/SoMuchForSubtlety/f1viewer/
    maintainer: SoMuchForSubtlety <s0muchfrsubtlety@gmail.com>
    formats:
      - deb
      - rpm
    recommends:
      - xclip
      - mpv
      - vlc
brews:
  - description: TUI client for F1TV
    homepage: https://github.com/SoMuchForSubtlety/f1viewer/
    folder: Formula
    tap:
      owner: SoMuchForSubtlety
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
