name: release

on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_GORELEASER }}
  macOs-build:
    runs-on: macos-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Build
        run: ./macOS-build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: f1viewer_${{ steps.get_version.outputs.VERSION }}_macOS
          path: f1viewer_${{ steps.get_version.outputs.VERSION }}_macOS_64-bit.tar.gz
